version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root      
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: messages
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 5
        volumes:
            - mysql_data:/var/lib/mysql  # Volumen persistente para datos
            - ./init-scripts:/docker-entrypoint-initdb.d  # Montar el script SQL
    adminer:
        container_name: myadminer
        image: adminer:latest
        restart: always
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: db
    app:
        container_name: myapp
        depends_on:
            db:
                condition: service_healthy
        build: ./
        ports:
            - "80:80"
    
    prometheus:
        container_name: myprometheus
        image: prom/mysqld-exporter
        ports:
            - "9104:9104"
        links:
            - db
        depends_on:
            db:
                condition: service_healthy

    
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_ALERTING_EXECUTE_ALERTS=false
        #volumes:
        #- grafana_data:/var/lib/grafana
        ports:
        - 3000:3000
        links:
        - prometheus
        depends_on:
        - prometheus
networks:
  default:
    driver: bridge

volumes:
    mysql_data:  # Volumen persistente para los datos de MySQL
