services:
    db:
        container_name: mydb
        image: mysql:latest
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root      
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: messages
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 5
        volumes:
            - mysql_data:/var/lib/mysql  # Volumen persistente para datos
            - ./init-scripts:/docker-entrypoint-initdb.d  # Montar el script SQL
        networks:
            - default

    adminer:
        container_name: myadminer
        image: adminer:latest
        restart: always
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: db
        networks:
            - default

    app:
        container_name: myapp
        depends_on:
            db:
                condition: service_healthy
        build: ./
        ports:
            - "80:80"
        networks:
            - default

    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        volumes:
            - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
        depends_on:
            - app
        ports:
            - "9090:9090"
        networks:
            - default

    mysql-exporter:
        container_name: mysql-exporter
        image: prom/mysqld-exporter
        command: 
            - --config.my-cnf=/cfg/.my.cnf
            - --mysqld.address=db:3306
        volumes:
            - "./.my.cnf:/cfg/.my.cnf"
        depends_on:
            - db
        ports:
            - 9104:9104
        networks:
            - default

    grafana:
        container_name: grafana
        image: grafana/grafana
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./grafana:/etc/grafana/provisioning/datasources
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        networks:
            - default

volumes:
    mysql_data:  # Volumen persistente para los datos de MySQL

networks:
    default:
        driver: bridge
        name: mynetwork
        