version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    adminer:
        container_name: myadminer
        image: adminer:latest
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: db
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"
