version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: messages
        volumes:
            - mysql_data:/var/lib/mysql  # Volumen persistente para datos
            - ./init-scripts:/docker-entrypoint-initdb.d  # Montar el script SQL
    adminer:
        container_name: myadminer
        image: adminer:latest
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: db
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"
volumes:
    mysql_data:  # Volumen persistente para los datos de MySQL
