global:
  scrape_interval: 3s

  external_labels:
    monitor: "app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "app"
    static_configs:
      - targets: ["app:80"]
    
  - job_name: "mysql_exporter"
    static_configs:
      - targets: ["mysql-exporter:9104"]